spring.application.name=drivers
spring.datasource.url=jdbc:postgresql://localhost:5332/drivers_db
spring.datasource.username=martini
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Spring Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=DRIVER

# Disable security for Swagger
spring.security.filter.dispatcher-types=REQUEST,ERROR,ASYNC


# Secret key for JWT signing
app.jwt.secret=${JWT_SECRET:UPeV+T8EnwMgMuvvxlYCH0bpHL65IYiunmvoAJPKllyORtf9LD4rAsfPLWZhhEPSMHl8D892PAhfNW/1kKoTsQ==}
app.jwt.expiration-ms=86400000